import React, { useMemo, useState } from 'react';
import * as XLSX from 'xlsx';
import { BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, XAxis, YAxis, Tooltip, ResponsiveContainer, Legend, ComposedChart, Area } from 'recharts';
import { LayoutDashboard, Table2, PlusCircle, Upload, Search, AlertTriangle, CheckCircle2, Trash2, Download, Plane, Globe2, Filter } from 'lucide-react';

const PAYMENT_KEY = 'sirva-payment-dashboard-records-v2';
const FLIGHT_KEY = 'sirva-flight-booking-records-v2';
const FX = { KRW: 1, USD: 1350, SGD: 1000, TWD: 42, JPY: 9.2, AUD: 890 };
const COLORS = ['#4285f4', '#f9ab00', '#ea4335', '#34a853', '#7b61ff', '#00a3ff'];
const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const monthOptions = ['All', ...months];
const periodOptions = [
  { label:'2026 전체', start:'2026-01-01', end:'2026-12-31' },
  { label:'1분기', start:'2026-01-01', end:'2026-03-31' },
  { label:'2분기', start:'2026-04-01', end:'2026-06-30' },
  { label:'3분기', start:'2026-07-01', end:'2026-09-30' },
  { label:'4분기', start:'2026-10-01', end:'2026-12-31' }
];

const rawPayments = [
  ['Taiwan','Jan','2026-01-12','872156','217761','RFC','CP26773','Ranjan Tukesh','SIRVA Fee','Expat-Relovc','CP26773_Tukesh Ranjan_INV217761_260312','A70001131','USD',987,'2026-05-11','PO312440','100003884','N60','PAID'],
  ['Taiwan','Feb','2026-02-12','871204','217353','RFC','CP281024','Gattani, Deepesh','Disbursement','Expat-Relovc','CP281024_Deepesh Gattani_INV217353_260312','A11080000','USD',8750,'2026-04-24','PO312440','100003886','N30','PAID'],
  ['Taiwan','Mar','2026-03-12','871359','2173532','CPTW','CP277208','Kwok, Ka Chun','SIRVA Fee','Expat-FurnRent','CP277208_Ken Kwok_INV2173532_260312','TA2102000','USD',6705,'2026-05-11','PO308846','100004327','N30','PAID'],
  ['Taiwan','Apr','2026-04-02','873160','218073','CPTW','CP279328','Chi, Xiang','Disbursement','Expat-Transport','CP79328_Tina X Chi_INV218073_260402','TA2102000','USD',21623,'2026-06-01','PO308846','100005725','N30','PAID'],
  ['Singapore','Apr','2026-04-02','875725','2180374','CPTW','CP278355','Kumar, Dinesh','SIRVA Fee','Expat-Relovc','CP278355_Dinesh Kumar_INV2180374_260402','SG100200','USD',1930,'2026-06-01','PO308846','100005725','N60','PAID'],
  ['Singapore','May','2026-05-14','875991','218455','CPSG','CP271555','Sam Bae','Disbursement','Expat-Tuition','CP271555_Sam Bae_INV218455_260514','SG100200','SGD',18900,'2026-06-20','PO318888','100006112','N30','PAID'],
  ['Korea','Jun','2026-06-02','879210','219001','CPKR','CP269477','Tracy Lu','SIRVA Fee','Expat-Relovc','CP269477_Tracy Lu_INV219001_260602','KR220100','USD',1450,'2026-06-30','PO320101','100006541','N60','PAYMENT_PENDING'],
  ['USA','Jul','2026-07-18','881008','219423','CPUS','CP280842','Shinae SA Kang','Disbursement','Expat-Tuition','CP280842_Shinae SA Kang_INV219423_260718','US330500','USD',22500,'2026-08-09','PO330882','100007011','N30','APPROVED'],
  ['Australia','Aug','2026-08-04','884019','219880','CPAU','CP257135','Sam Bae','Disbursement','Expat-Tuition','CP257135_Sam Bae_INV219880_260804','AU440210','AUD',14800,'2026-08-29','PO340019','100007508','N30','PAID'],
  ['India','Sep','2026-09-03','886201','220115','CPIN','CP176840','San Baek','SIRVA Fee','Expat-Relovc','CP176840_San Baek_INV220115_260903','IN120410','USD',1210,'2026-09-28','PO350010','100008000','N60','PAID'],
  ['Japan','Oct','2026-10-10','889904','220771','CPJP','CP226805','Deepak Malani','Disbursement','Expat-Tuition','CP226805_Deepak Malani_INV220771_261010','JP700011','JPY',1650000,'2026-10-30','PO360120','100008551','N30','RECEIVED'],
  ['Hong Kong','Nov','2026-11-12','892001','221008','CPHK','CP256211','Jatin Chaudhary','SIRVA Fee','Expat-Relovc','CP256211_Jatin Chaudhary_INV221008_261112','HK103019','USD',1640,'2026-11-29','PO370119','100009010','N60','APPROVED'],
  ['USA','Dec','2026-12-08','895112','221554','CPUS','CP900625','Michael Sommers','Disbursement','Expat-Transport','CP900625_Michael Sommers_INV221554_261208','US300200','USD',6200,'2026-12-24','PO380225','100009770','N30','PAID']
];
const sampleRows = rawPayments.map((r,i)=>({ id:`p${i+1}`, country:r[0], invoiceMonth:r[1], invoiceDate:r[2], fileNumber:r[3], invoiceNo:r[4], entity:r[5], employeeId:r[6], employeeName:r[7], serviceType:r[8], category:r[9], description:r[10], costCenter:r[11], currency:r[12], amount:r[13], paymentDate:r[14], poNumber:r[15], iacDocNo:r[16], paymentItem:r[17], status:r[18] }));

const rawFlights = [
  ['India','2026-05-04','Repat','CP226805','Deepak Malani','N','Coupang, Corp.','Mathilde','MALANI/DEEPAK KUMAR MR','Employee','2026-05-10','','ICN','BLR',1628000,62700,'XXXXXXXXXXXX2880','','CP226805_Deepak Malani(E)','A70001131','BOOKED'],
  ['USA','2026-05-04','HLF','CP280842','Shinae SA Kang','N','Coupang, Corp.','Grace','KANG/SHINAE MS','Employee','2026-07-25','2026-08-08','ICN','IAD',4263500,164100,'XXXXXXXXXXXX2880','','CP280842_Shinae SA Kang(E)','A11080000','BOOKED'],
  ['USA','2026-05-04','HLF','CP280842','Shinae SA Kang','N','Coupang, Corp.','Grace','KIM/MIN SHIN MS','Child','2026-07-25','2026-08-21','ICN','IAD',3506500,135000,'XXXXXXXXXXXX2880','','CP280842_Shinae SA Kang(C)','A11080000','BOOKED'],
  ['India','2026-05-06','HLF','CP176840','San Baek','N','Coupang, Corp.','Lee','BAEK/SAN MR','Employee','2026-05-16','','ICN','TRV',1134000,0,'XXXXXXXXXXXX2880','수기매입','CP176840_San Baek(E)','A12041000','BOOKED'],
  ['USA','2026-05-06','HLF','CP176840','San Baek','N','Coupang, Corp.','Lee','BAEK/HA RU MISS','Child','2026-06-16','2026-06-20','ICN','HNL',2211600,85100,'XXXXXXXXXXXX2880','','CP176840_San Baek(C)','A12041000','BOOKED'],
  ['USA','2026-05-06','HLF','CP176840','San Baek','N','Coupang, Corp.','Lee','BAEK/MIN KYONG SONG MS','Spouse','2026-06-16','2026-06-20','ICN','HNL',2683100,103300,'XXXXXXXXXXXX2880','','CP176840_San Baek(S)','A12041000','BOOKED'],
  ['Australia','2026-05-07','HLF','CP257135','Sam Bae','N','Coupang, Corp.','Mathilde','BAE/SOPHIA YERANG MS','Child','2026-08-01','2026-08-09','ICN','SYD',2718800,104700,'XXXXXXXXXXXX2880','','CP257135_Sam Bae(C)','A70108000','BOOKED'],
  ['Australia','2026-05-07','HLF','CP257135','Sam Bae','N','Coupang, Corp.','Mathilde','BAE/ELISHA SARANG MS','Child','2026-08-01','2026-08-09','ICN','SYD',2718800,104700,'XXXXXXXXXXXX2880','','CP257135_Sam Bae(C)','A70108000','BOOKED'],
  ['Japan','2026-06-12','STA','CP256211','Jatin Chaudhary','N','Coupang, Corp.','Grace','CHAUDHARY/PRIYA JATIN MS','Spouse','2026-06-17','2026-08-15','ICN','NRT',1526000,58700,'XXXXXXXXXXXX2880','','CP256211_Jatin Chaudhary(S)','A1031019','BOOKED'],
  ['Singapore','2026-07-08','HLF','CP269477','Tracy Lu','N','Coupang, Corp.','Brandon','SANKARAN/SANDHYA MS','Spouse','2026-08-12','','ICN','SIN',1784000,69200,'XXXXXXXXXXXX2880','','CP269477_Tracy Lu(S)','A7032610','BOOKED'],
  ['Taiwan','2026-08-14','Repat','CP271555','Sam Bae','N','Coupang, Corp.','Mathilde','BAE/SAM MR','Employee','2026-08-31','','ICN','TPE',814800,31400,'XXXXXXXXXXXX2880','','CP271555_Sam Bae(E)','A70108000','BOOKED'],
  ['Hong Kong','2026-09-03','HLF','CP900625','Michael Sommers','N','Coupang, Corp.','Brandon','SOMMERS/LILLY SAROM MRS','Spouse','2026-09-22','','ICN','HKG',1737000,66900,'XXXXXXXXXXXX2880','','CP900625_Michael Sommers(S)','A3002000','BOOKED'],
  ['Korea','2026-10-11','STA','CP141524','Salil Patil','N','Coupang, Corp.','Lee','PATIL/KAVIN MSTR','Child','2026-10-29','','BOM','ICN',677800,26100,'XXXXXXXXXXXX2880','','CP141524_Salil Patil(C)','A11036000','BOOKED'],
  ['India','2026-11-04','HLF','CP141524','Salil Patil','N','Coupang, Corp.','Lee','PATIL/SAMAR MSTR','Child','2026-11-20','','ICN','BOM',677800,26100,'XXXXXXXXXXXX2880','','CP141524_Salil Patil(C)','A11036000','PENDING'],
  ['USA','2026-12-02','Repat','CP273263','Matthew Welden','N','Coupang, Corp.','Guilherme','WELDEN/MATTHEW TODD MR','Employee','2026-12-18','','ICN','SEA',2684600,103300,'XXXXXXXXXXXX2880','','CP273263_Matthew Welden(E)','A11260000','BOOKED']
];
const sampleFlights = rawFlights.map((r,i)=>({ id:`f${i+1}`, country:r[0], bookingDate:r[1], category:r[2], employeeId:r[3], employeeName:r[4], pil:r[5], entity:r[6], caseManager:r[7], passengerName:r[8], relationship:r[9], departureDate1:r[10], departureDate2:r[11], departure1:r[12], departure2:r[13], airfare:r[14], trxFee:r[15], card:r[16], remark:r[17], iaccDetail:r[18], costCenter:r[19], status:r[20] }));

const paymentFields = ['country','invoiceMonth','invoiceDate','fileNumber','invoiceNo','entity','employeeId','employeeName','serviceType','category','description','costCenter','currency','amount','normalizedKrw','exchangeRate','paymentDate','poNumber','iacDocNo','paymentItem','status'];
const paymentLabels = { country:'Country', invoiceMonth:'Invoice Month', invoiceDate:'Invoice Date', fileNumber:'File Number', invoiceNo:'Invoice No', entity:'Entity', employeeId:'Employee ID', employeeName:'Employee Name', serviceType:'Service Type', category:'Category', description:'Text Description', costCenter:'Cost Center', currency:'Currency', amount:'Original Amount', normalizedKrw:'Normalized KRW', exchangeRate:'FX Rate', paymentDate:'Payment Date', poNumber:'PO', iacDocNo:'IAC Doc #', paymentItem:'PO Payment Item', status:'Status' };
const flightFields = ['country','bookingDate','category','employeeId','employeeName','pil','entity','caseManager','passengerName','relationship','departureDate1','departureDate2','departure1','departure2','currency','airfare','trxFee','normalizedKrw','exchangeRate','card','remark','iaccDetail','costCenter','status'];
const flightLabels = { country:'Country', bookingDate:'Booking Date', category:'Category', employeeId:'EE ID', employeeName:'Employee Name', pil:'PIL', entity:'Entity', caseManager:'Case Manager', passengerName:'Passenger Name', relationship:'Relationship', departureDate1:'Departure Date 1', departureDate2:'Departure Date 2', departure1:'Departure 1', departure2:'Departure 2', currency:'Currency', airfare:'Airfare', trxFee:'TRX Fee', normalizedKrw:'Normalized KRW', exchangeRate:'FX Rate', card:'CARD', remark:'Remark', iaccDetail:'iACC Detail', costCenter:'Cost Center', status:'Status' };

function load(key, fallback){ try { return JSON.parse(localStorage.getItem(key)) || fallback; } catch { return fallback; } }
function save(key, rows){ localStorage.setItem(key, JSON.stringify(rows)); }
function num(v){ return Number(String(v ?? 0).replace(/[₩$,]/g,'')) || 0; }
function fx(currency){ return FX[String(currency || 'KRW').toUpperCase()] || 1; }
function krw(v, currency='KRW'){ return Math.round(num(v) * fx(currency)); }
function paymentKrw(r){ return r.normalizedKrw ? num(r.normalizedKrw) : krw(r.amount, r.currency || 'USD'); }
function flightKrw(r){ return r.normalizedKrw ? num(r.normalizedKrw) : krw(num(r.airfare)+num(r.trxFee), r.currency || 'KRW'); }
function ymd(d){ return String(d || '').slice(0,10); }
function inRange(date, start, end){ const d = ymd(date); return (!start || d >= start) && (!end || d <= end); }
function monthFromDate(d){ const m = new Date(d).getMonth(); return Number.isFinite(m) && m >= 0 ? months[m] : 'Unknown'; }
function monthIndex(m){ return months.indexOf(String(m).slice(0,3)); }
function getRaw(raw, ...names){ for (const n of names){ const k = Object.keys(raw).find(x => x.trim().toLowerCase() === n.toLowerCase()); if(k) return raw[k]; } return ''; }
function paymentDupKey(r){ return [r.invoiceNo, r.employeeId, r.fileNumber, r.amount].map(v=>String(v||'').trim().toLowerCase()).join('|'); }
function flightDupKey(r){ return [r.bookingDate, r.employeeId, r.passengerName, r.departureDate1, r.departure1, r.departure2, r.airfare].map(v=>String(v||'').trim().toLowerCase()).join('|'); }
function makeExcelDate(v){ if(typeof v === 'number'){ const d = XLSX.SSF.parse_date_code(v); if(d) return `${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`; } return String(v || ''); }
function inferCountryFromRoute(code){ const c = String(code || '').toUpperCase(); const map = { ICN:'Korea', GMP:'Korea', PUS:'Korea', BLR:'India', TRV:'India', BOM:'India', DEL:'India', IAD:'USA', HNL:'USA', SEA:'USA', LAX:'USA', JFK:'USA', SYD:'Australia', MEL:'Australia', SIN:'Singapore', TPE:'Taiwan', TYO:'Japan', NRT:'Japan', HND:'Japan', HKG:'Hong Kong' }; return map[c] || 'Unknown'; }
function flightCountry(r){ return r.country || inferCountryFromRoute(r.departure2) || inferCountryFromRoute(r.departure1) || 'Unknown'; }
function normalizePaymentRow(r){ const currency = r.currency || 'USD'; return { ...r, currency, exchangeRate:r.exchangeRate || fx(currency), normalizedKrw: r.normalizedKrw || paymentKrw({...r,currency}) }; }
function normalizeFlightRow(r){ const currency = r.currency || 'KRW'; return { ...r, country:r.country || flightCountry(r), currency, exchangeRate:r.exchangeRate || fx(currency), normalizedKrw: r.normalizedKrw || flightKrw({...r,currency}) }; }
function normalizePayment(raw){ const currency=getRaw(raw,'Currency') || 'USD'; const amount=num(getRaw(raw,'Amount','USD','Invoice Amount','Total Amount','Payment Amount')); return normalizePaymentRow({ id:crypto.randomUUID(), country:getRaw(raw,'Country') || 'Unknown', invoiceMonth:getRaw(raw,'Invoice Month','Month','Invoice date (Month)') || '', invoiceDate:makeExcelDate(getRaw(raw,'Invoice Date','Invoice date')), fileNumber:getRaw(raw,'File Number','File Num','File No') || '', invoiceNo:getRaw(raw,'Invoice No','Invoice Number','Invoice No.') || '', entity:getRaw(raw,'Entity') || '', employeeId:getRaw(raw,'Employee ID','Employee','EE ID') || '', employeeName:getRaw(raw,'Employee Name') || '', serviceType:getRaw(raw,'SIRVA service type','Service Type','Sirva Service Type') || '', category:getRaw(raw,'Category','Item','Item Details') || '', description:getRaw(raw,'Text Description (A/C)','Text Description','Description') || '', costCenter:getRaw(raw,'Cost Center','Cost Cen') || '', currency, amount, paymentDate:makeExcelDate(getRaw(raw,'Payment Date')), poNumber:getRaw(raw,'PO','PO Number') || '', iacDocNo:getRaw(raw,'IAC Doc #','IAC Doc','IAC Document') || '', paymentItem:getRaw(raw,'PO Payment Item','Payment Item') || '', status:getRaw(raw,'Status') || 'RECEIVED' }); }
function normalizeFlight(raw){ const departure2 = getRaw(raw,'Departure 2') || ''; const currency = getRaw(raw,'Currency') || 'KRW'; return normalizeFlightRow({ id:crypto.randomUUID(), country:getRaw(raw,'Country') || inferCountryFromRoute(departure2), bookingDate:makeExcelDate(getRaw(raw,'Booking Date','Booking Dat')), category:getRaw(raw,'Category') || '', employeeId:getRaw(raw,'EE ID','Employee ID','Employee') || '', employeeName:getRaw(raw,'Employee Name') || '', pil:getRaw(raw,'Pil','PIL') || '', entity:getRaw(raw,'Entity') || '', caseManager:getRaw(raw,'Case Manager') || '', passengerName:getRaw(raw,'Passenger Name') || '', relationship:getRaw(raw,'Relationship') || '', departureDate1:makeExcelDate(getRaw(raw,'Departure Date 1','Departure Date')), departureDate2:makeExcelDate(getRaw(raw,'Departure Date 2')), departure1:getRaw(raw,'Departure 1','Departure') || '', departure2, currency, airfare:num(getRaw(raw,'Airfare')), trxFee:num(getRaw(raw,'TRX Fee','TRX fee')), card:getRaw(raw,'CARD','Card') || '', remark:getRaw(raw,'Remark') || '', iaccDetail:getRaw(raw,'iACC Detail','iAC Detail','IACC Detail') || '', costCenter:getRaw(raw,'Cost Center') || '', status:getRaw(raw,'Status') || 'BOOKED' }); }

function FilterBar({ filters, setFilters, countries, categories }){
  return <div className="filterBar"><div><Filter size={16}/><b>Filter</b></div><label>기간<select value={filters.period} onChange={e=>setFilters({...filters,period:e.target.value})}>{periodOptions.map(p=><option key={p.label}>{p.label}</option>)}</select></label><label>월<select value={filters.month} onChange={e=>setFilters({...filters,month:e.target.value})}>{monthOptions.map(m=><option key={m}>{m}</option>)}</select></label><label>국가<select value={filters.country} onChange={e=>setFilters({...filters,country:e.target.value})}><option>All</option>{countries.map(c=><option key={c}>{c}</option>)}</select></label><label>구분<select value={filters.costType} onChange={e=>setFilters({...filters,costType:e.target.value})}><option>All</option><option>Tuition</option><option>Flight</option></select></label><label>카테고리<select value={filters.category} onChange={e=>setFilters({...filters,category:e.target.value})}><option>All</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label></div>
}

function App(){
  const [payments, setPayments] = useState(()=>load(PAYMENT_KEY, sampleRows).map(normalizePaymentRow));
  const [flights, setFlights] = useState(()=>load(FLIGHT_KEY, sampleFlights).map(normalizeFlightRow));
  const [view, setView] = useState('overviewDashboard');
  const [query, setQuery] = useState('');
  const [uploadResult, setUploadResult] = useState(null);
  const [filters, setFilters] = useState({ period:'2026 전체', month:'All', country:'All', costType:'All', category:'All' });
  const [paymentForm, setPaymentForm] = useState({ country:'Taiwan', invoiceMonth:'Apr', invoiceDate:'2026-04-02', fileNumber:'', invoiceNo:'', entity:'CPTW', employeeId:'', employeeName:'', serviceType:'SIRVA Fee', category:'Expat-Relovc', description:'', costCenter:'', currency:'USD', amount:'', normalizedKrw:'', exchangeRate:'1350', paymentDate:'', poNumber:'', iacDocNo:'', paymentItem:'', status:'RECEIVED' });
  const [flightForm, setFlightForm] = useState({ country:'', bookingDate:'2026-05-06', category:'HLF', employeeId:'', employeeName:'', pil:'N', entity:'Coupang, Corp.', caseManager:'', passengerName:'', relationship:'Employee', departureDate1:'', departureDate2:'', departure1:'ICN', departure2:'', currency:'KRW', airfare:'', trxFee:'', normalizedKrw:'', exchangeRate:'1', card:'XXXXXXXXXXXX2880', remark:'', iaccDetail:'', costCenter:'', status:'BOOKED' });

  const setPaymentSave = next => { const n = next.map(normalizePaymentRow); setPayments(n); save(PAYMENT_KEY, n); };
  const setFlightSave = next => { const n = next.map(normalizeFlightRow); setFlights(n); save(FLIGHT_KEY, n); };
  const period = periodOptions.find(p=>p.label===filters.period) || periodOptions[0];
  const filteredPaymentBase = payments.filter(r => inRange(r.invoiceDate || r.paymentDate, period.start, period.end) && (filters.month==='All' || r.invoiceMonth===filters.month) && (filters.country==='All' || r.country===filters.country) && (filters.category==='All' || r.category===filters.category));
  const filteredFlightBase = flights.filter(r => inRange(r.bookingDate, period.start, period.end) && (filters.month==='All' || monthFromDate(r.bookingDate)===filters.month) && (filters.country==='All' || flightCountry(r)===filters.country) && (filters.category==='All' || r.category===filters.category));
  const countries = [...new Set([...payments.map(r=>r.country || 'Unknown'), ...flights.map(flightCountry)])].sort();
  const categories = [...new Set([...payments.map(r=>r.category || 'Unknown'), ...flights.map(r=>r.category || 'Unknown')])].sort();

  const overviewStats = useMemo(()=>{
    const pay = filters.costType==='Flight' ? [] : filteredPaymentBase;
    const flt = filters.costType==='Tuition' ? [] : filteredFlightBase;
    const tuitionAnnual = pay.reduce((s,r)=>s+paymentKrw(r),0);
    const flightAnnual = flt.reduce((s,r)=>s+flightKrw(r),0);
    const byMonth = months.map(month => {
      const tuition = pay.filter(r=>r.invoiceMonth===month).reduce((s,r)=>s+paymentKrw(r),0);
      const flight = flt.filter(r=>monthFromDate(r.bookingDate)===month).reduce((s,r)=>s+flightKrw(r),0);
      return { month, Tuition:tuition, Flight:flight, Total:tuition+flight };
    });
    const byCountry = [...new Set([...pay.map(r=>r.country || 'Unknown'), ...flt.map(flightCountry)])].map(country => {
      const tuition = pay.filter(r=>(r.country || 'Unknown')===country).reduce((s,r)=>s+paymentKrw(r),0);
      const flight = flt.filter(r=>flightCountry(r)===country).reduce((s,r)=>s+flightKrw(r),0);
      return { country, tuition, flight, total:tuition+flight, tuitionCount:pay.filter(r=>(r.country || 'Unknown')===country).length, flightCount:flt.filter(r=>flightCountry(r)===country).length };
    }).sort((a,b)=>b.total-a.total);
    const topMonth = byMonth.reduce((max,m)=>m.Total > max.Total ? m : max, { month:'-', Total:0 });
    return { tuitionAnnual, flightAnnual, grandTotal:tuitionAnnual+flightAnnual, byCountry, byMonth, topMonth, totalRecords:pay.length+flt.length };
  },[filteredPaymentBase, filteredFlightBase, filters.costType]);

  const payStats = useMemo(()=>{
    const data = filteredPaymentBase; const total = data.reduce((s,r)=>s+paymentKrw(r),0);
    const sirva = data.filter(r=>String(r.serviceType).toLowerCase().includes('sirva')).reduce((s,r)=>s+paymentKrw(r),0);
    const disb = data.filter(r=>String(r.serviceType).toLowerCase().includes('disbur')).reduce((s,r)=>s+paymentKrw(r),0);
    const byMonth = months.map(m=>({ month:m, SIRVA:data.filter(r=>r.invoiceMonth===m && String(r.serviceType).toLowerCase().includes('sirva')).reduce((s,r)=>s+paymentKrw(r),0), Disbursement:data.filter(r=>r.invoiceMonth===m && String(r.serviceType).toLowerCase().includes('disbur')).reduce((s,r)=>s+paymentKrw(r),0)}));
    const byCountry = [...new Set(data.map(r=>r.country || 'Unknown'))].map(c=>({ country:c, total:data.filter(r=>r.country===c).reduce((s,r)=>s+paymentKrw(r),0), sirva:data.filter(r=>r.country===c && String(r.serviceType).toLowerCase().includes('sirva')).reduce((s,r)=>s+paymentKrw(r),0), disbursement:data.filter(r=>r.country===c && String(r.serviceType).toLowerCase().includes('disbur')).reduce((s,r)=>s+paymentKrw(r),0)}));
    return { total, sirva, disb, byMonth, byCountry };
  },[filteredPaymentBase]);

  const flightStats = useMemo(()=>{
    const data = filteredFlightBase; const totalAirfare = data.reduce((s,r)=>s+krw(r.airfare,r.currency),0); const totalTrx = data.reduce((s,r)=>s+krw(r.trxFee,r.currency),0);
    const byMonth = months.map(m=>({ month:m, Airfare:data.filter(r=>monthFromDate(r.bookingDate)===m).reduce((s,r)=>s+krw(r.airfare,r.currency),0), TRX:data.filter(r=>monthFromDate(r.bookingDate)===m).reduce((s,r)=>s+krw(r.trxFee,r.currency),0), Count:data.filter(r=>monthFromDate(r.bookingDate)===m).length }));
    const byCategory = [...new Set(data.map(r=>r.category || 'Unknown'))].map(category=>({ category, amount:data.filter(r=>(r.category||'Unknown')===category).reduce((s,r)=>s+flightKrw(r),0), count:data.filter(r=>(r.category||'Unknown')===category).length }));
    const byRelation = [...new Set(data.map(r=>r.relationship || 'Unknown'))].map(name=>({ name, value:data.filter(r=>(r.relationship||'Unknown')===name).length }));
    const byManager = [...new Set(data.map(r=>r.caseManager || 'Unassigned'))].map(name=>({ name, count:data.filter(r=>(r.caseManager||'Unassigned')===name).length }));
    return { totalAirfare, totalTrx, pax:data.length, employees:new Set(data.map(r=>r.employeeId).filter(Boolean)).size, byMonth, byCategory, byRelation, byManager };
  },[filteredFlightBase]);

  const isFlight = view.startsWith('flight'); const isOverview = view==='overviewDashboard';
  const titleMap = { overviewDashboard:'통합 비용 대시보드', paymentDashboard:'학비/교육비 대시보드', paymentTable:'Payment Tracker', paymentForm:'Payment 개별 등록', paymentUpload:'Payment Excel Upload', flightDashboard:'항공권 대시보드', flightTable:'항공권 데이터 관리', flightForm:'항공권 개별 등록', flightUpload:'항공권 Excel Upload' };
  const filteredPayments = payments.filter(r => JSON.stringify(r).toLowerCase().includes(query.toLowerCase()));
  const filteredFlights = flights.filter(r => JSON.stringify(r).toLowerCase().includes(query.toLowerCase()));

  function addPayment(e){ e.preventDefault(); const record=normalizePaymentRow({...paymentForm,id:crypto.randomUUID(),amount:num(paymentForm.amount),normalizedKrw:paymentForm.normalizedKrw?num(paymentForm.normalizedKrw):'',exchangeRate:paymentForm.exchangeRate||fx(paymentForm.currency)}); if(payments.some(r=>paymentDupKey(r)===paymentDupKey(record))) return alert('중복 Payment 데이터입니다.'); setPaymentSave([record,...payments]); setView('paymentTable'); }
  function addFlight(e){ e.preventDefault(); const record=normalizeFlightRow({...flightForm,id:crypto.randomUUID(),country:flightForm.country || inferCountryFromRoute(flightForm.departure2),airfare:num(flightForm.airfare),trxFee:num(flightForm.trxFee),normalizedKrw:flightForm.normalizedKrw?num(flightForm.normalizedKrw):'',exchangeRate:flightForm.exchangeRate||fx(flightForm.currency)}); if(flights.some(r=>flightDupKey(r)===flightDupKey(record))) return alert('중복 항공권 데이터입니다.'); setFlightSave([record,...flights]); setFlightForm({...flightForm, employeeId:'', employeeName:'', passengerName:'', airfare:'', trxFee:'', normalizedKrw:'', iaccDetail:''}); setView('flightTable'); }

  async function onUpload(e, type){ const file=e.target.files?.[0]; if(!file) return; const data=await file.arrayBuffer(); const wb=XLSX.read(data); const json=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]], { defval:'' }); if(type==='flight'){ const incoming=json.map(normalizeFlight).filter(r=>r.employeeId || r.passengerName || r.bookingDate); const keys=new Set(flights.map(flightDupKey)); const fresh=[]; const duplicated=[]; incoming.forEach(r=>{ const k=flightDupKey(r); if(keys.has(k)) duplicated.push(r); else { keys.add(k); fresh.push(r); }}); setFlightSave([...fresh,...flights]); setUploadResult({type,total:incoming.length,inserted:fresh.length,duplicated:duplicated.length}); } else { const incoming=json.map(normalizePayment).filter(r=>r.invoiceNo || r.fileNumber || r.employeeId); const keys=new Set(payments.map(paymentDupKey)); const fresh=[]; const duplicated=[]; incoming.forEach(r=>{ const k=paymentDupKey(r); if(keys.has(k)) duplicated.push(r); else { keys.add(k); fresh.push(r); }}); setPaymentSave([...fresh,...payments]); setUploadResult({type,total:incoming.length,inserted:fresh.length,duplicated:duplicated.length}); } e.target.value=''; }

  function exportExcel(){ const fields = isOverview ? ['country','tuition','flight','total','tuitionCount','flightCount'] : isFlight ? flightFields : paymentFields; const labels = isOverview ? {country:'Country',tuition:'Tuition KRW',flight:'Flight KRW',total:'Total KRW',tuitionCount:'Tuition Count',flightCount:'Flight Count'} : isFlight ? flightLabels : paymentLabels; const data = isOverview ? overviewStats.byCountry : isFlight ? flights : payments; const ws=XLSX.utils.json_to_sheet(data.map(r=>Object.fromEntries(fields.map(f=>[labels[f], r[f]])))); const wb=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb,ws,isOverview?'Integrated':isFlight?'Flight':'Payment'); XLSX.writeFile(wb,isOverview?'integrated-cost-dashboard.xlsx':isFlight?'flight-booking-data.xlsx':'sirva-payment-tracker.xlsx'); }

  return <div className="app"><aside className="side"><h1><span>C</span> Global<br/>Mobility</h1><button onClick={()=>setView('overviewDashboard')} className={view==='overviewDashboard'?'active':''}><Globe2/> 통합 대시보드</button><div className="sideGroup">Tuition / Payment</div><button onClick={()=>setView('paymentDashboard')} className={view==='paymentDashboard'?'active':''}><LayoutDashboard/> Payment 대시보드</button><button onClick={()=>setView('paymentTable')} className={view==='paymentTable'?'active':''}><Table2/> Payment 데이터</button><button onClick={()=>setView('paymentForm')} className={view==='paymentForm'?'active':''}><PlusCircle/> Payment 등록</button><button onClick={()=>setView('paymentUpload')} className={view==='paymentUpload'?'active':''}><Upload/> Payment 업로드</button><div className="sideGroup">Flight Booking</div><button onClick={()=>setView('flightDashboard')} className={view==='flightDashboard'?'active':''}><Plane/> 항공권 대시보드</button><button onClick={()=>setView('flightTable')} className={view==='flightTable'?'active':''}><Table2/> 항공권 데이터</button><button onClick={()=>setView('flightForm')} className={view==='flightForm'?'active':''}><PlusCircle/> 항공권 등록</button><button onClick={()=>setView('flightUpload')} className={view==='flightUpload'?'active':''}><Upload/> 항공권 업로드</button></aside><main><header><div><p>{isOverview?'Normalized KRW / Integrated Cost View':isFlight?'Flight Booking / Airfare Cost':'Global Mobility Tuition / Education Cost'}</p><h2>{titleMap[view]}</h2></div><button className="ghost" onClick={exportExcel}><Download size={16}/> Export Excel</button></header>
    {(view.includes('Dashboard')) && <FilterBar filters={filters} setFilters={setFilters} countries={countries} categories={categories}/>} 
    {view==='overviewDashboard' && <Overview stats={overviewStats}/>} 
    {view==='paymentDashboard' && <PaymentDash stats={payStats}/>} 
    {view==='flightDashboard' && <FlightDash stats={flightStats}/>} 
    {view==='paymentTable' && <DataTable rows={filteredPayments} allRows={payments} setRows={setPaymentSave} fields={paymentFields} labels={paymentLabels} query={query} setQuery={setQuery} reset={()=>setPaymentSave(sampleRows)} placeholder="국가, 직원명, Invoice No, PO 검색" moneyFields={['amount','normalizedKrw','exchangeRate']} />}
    {view==='flightTable' && <DataTable rows={filteredFlights} allRows={flights} setRows={setFlightSave} fields={flightFields} labels={flightLabels} query={query} setQuery={setQuery} reset={()=>setFlightSave(sampleFlights)} placeholder="국가, 직원명, 탑승객, 항공구간, Cost Center 검색" moneyFields={['airfare','trxFee','normalizedKrw','exchangeRate']} />}
    {view==='paymentForm' && <RecordForm fields={paymentFields} labels={paymentLabels} form={paymentForm} setForm={setPaymentForm} submit={addPayment} required={['invoiceNo','employeeId','amount']} />}
    {view==='flightForm' && <RecordForm fields={flightFields} labels={flightLabels} form={flightForm} setForm={setFlightForm} submit={addFlight} required={['bookingDate','employeeId','passengerName','airfare']} />}
    {view==='paymentUpload' && <UploadPanel type="payment" onUpload={onUpload} result={uploadResult} desc="Payment Tracker 엑셀 업로드: 원본 금액/통화는 보존하고, Normalized KRW를 별도 계산합니다." />}
    {view==='flightUpload' && <UploadPanel type="flight" onUpload={onUpload} result={uploadResult} desc="항공권 엑셀 업로드: Airfare + TRX Fee를 KRW 기준으로 정규화하고 중복을 제외합니다." />}
  </main></div>;
}

function Overview({stats}){ return <section className="dash"><div className="hero four"><div><span>Annual Usage Cost</span><strong>₩{stats.grandTotal.toLocaleString()}</strong><small>정규화 KRW 기준</small></div><div className="split"><b>Tuition / Education</b><strong>₩{stats.tuitionAnnual.toLocaleString()}</strong><small>FX normalized</small></div><div className="split orange"><b>Flight Booking</b><strong>₩{stats.flightAnnual.toLocaleString()}</strong><small>Airfare + TRX Fee</small></div><div className="split purple"><b>Monthly Peak</b><strong>{stats.topMonth.month}</strong><small>₩{stats.topMonth.Total.toLocaleString()}</small></div></div><div className="panel wide"><h3>월별 사용 비용</h3><ResponsiveContainer height={320}><ComposedChart data={stats.byMonth}><XAxis dataKey="month"/><YAxis/><Tooltip/><Legend/><Bar dataKey="Tuition" stackId="a" fill="#4285f4"/><Bar dataKey="Flight" stackId="a" fill="#f9ab00"/><Line type="monotone" dataKey="Total" stroke="#ea4335" strokeWidth={3}/></ComposedChart></ResponsiveContainer></div><div className="panel wide"><h3>국가별 학비/항공권 비용 비교</h3><ResponsiveContainer height={330}><BarChart data={stats.byCountry}><XAxis dataKey="country"/><YAxis/><Tooltip/><Legend/><Bar dataKey="tuition" name="Tuition" fill="#4285f4"/><Bar dataKey="flight" name="Flight" fill="#f9ab00"/></BarChart></ResponsiveContainer></div><div className="panel"><h3>국가별 비용 상세</h3><div className="tableWrap short"><table><thead><tr><th>Country</th><th>Tuition KRW</th><th>Flight KRW</th><th>Total KRW</th><th>Tuition Count</th><th>Flight Count</th></tr></thead><tbody>{stats.byCountry.map(c=><tr key={c.country}><td>{c.country}</td><td>₩{c.tuition.toLocaleString()}</td><td>₩{c.flight.toLocaleString()}</td><td>₩{c.total.toLocaleString()}</td><td>{c.tuitionCount}</td><td>{c.flightCount}</td></tr>)}</tbody></table></div></div><div className="panel"><h3>월별 비용 상세</h3><table><thead><tr><th>Month</th><th>Tuition</th><th>Flight</th><th>Total</th></tr></thead><tbody>{stats.byMonth.map(m=><tr key={m.month}><td>{m.month}</td><td>₩{m.Tuition.toLocaleString()}</td><td>₩{m.Flight.toLocaleString()}</td><td>₩{m.Total.toLocaleString()}</td></tr>)}</tbody></table></div></section> }
function PaymentDash({stats}){ return <section className="dash"><div className="hero"><div><span>Tuition Spend</span><strong>₩{stats.total.toLocaleString()}</strong></div><div className="split"><b>SIRVA Fee</b><strong>₩{stats.sirva.toLocaleString()}</strong><small>{stats.total?((stats.sirva/stats.total)*100).toFixed(1):0}%</small></div><div className="split orange"><b>Disbursement</b><strong>₩{stats.disb.toLocaleString()}</strong><small>{stats.total?((stats.disb/stats.total)*100).toFixed(1):0}%</small></div></div><div className="panel wide"><h3>월별 학비/교육비</h3><ResponsiveContainer height={300}><BarChart data={stats.byMonth}><XAxis dataKey="month"/><YAxis/><Tooltip/><Legend/><Bar dataKey="SIRVA" stackId="a" fill="#4285f4"/><Bar dataKey="Disbursement" stackId="a" fill="#f9ab00"/></BarChart></ResponsiveContainer></div><div className="grid3">{stats.byCountry.map(c=><div className="country" key={c.country}><h3>{c.country}</h3><strong>₩{c.total.toLocaleString()}</strong><ResponsiveContainer height={130}><PieChart><Pie data={[{name:'SIRVA Fee',value:c.sirva},{name:'Disbursement',value:c.disbursement}]} dataKey="value" innerRadius={34} outerRadius={55}>{[0,1].map(i=><Cell key={i} fill={COLORS[i]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><p><span>SIRVA Fee</span><b>₩{c.sirva.toLocaleString()}</b></p><p><span>Disbursement</span><b>₩{c.disbursement.toLocaleString()}</b></p></div>)}</div></section> }
function FlightDash({stats}){ return <section className="dash"><div className="hero four"><div><span>Total Flight Cost</span><strong>₩{(stats.totalAirfare+stats.totalTrx).toLocaleString()}</strong></div><div className="split"><b>Airfare</b><strong>₩{stats.totalAirfare.toLocaleString()}</strong><small>항공권 금액</small></div><div className="split orange"><b>TRX Fee</b><strong>₩{stats.totalTrx.toLocaleString()}</strong><small>발권 수수료</small></div><div className="split purple"><b>Passengers</b><strong>{stats.pax.toLocaleString()}</strong><small>{stats.employees} employees</small></div></div><div className="panel wide"><h3>월별 항공권 비용</h3><ResponsiveContainer height={300}><BarChart data={stats.byMonth}><XAxis dataKey="month"/><YAxis/><Tooltip/><Legend/><Bar dataKey="Airfare" stackId="a" fill="#4285f4"/><Bar dataKey="TRX" stackId="a" fill="#f9ab00"/></BarChart></ResponsiveContainer></div><div className="grid3"><div className="country"><h3>Relationship</h3><ResponsiveContainer height={170}><PieChart><Pie data={stats.byRelation} dataKey="value" nameKey="name" innerRadius={42} outerRadius={68}>{stats.byRelation.map((_,i)=><Cell key={i} fill={COLORS[i%COLORS.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="panel"><h3>Category Breakdown</h3><table><tbody>{stats.byCategory.map(c=><tr key={c.category}><td>{c.category}</td><td>{c.count}건</td><td>₩{c.amount.toLocaleString()}</td></tr>)}</tbody></table></div><div className="panel"><h3>Case Manager</h3><table><tbody>{stats.byManager.map(c=><tr key={c.name}><td>{c.name}</td><td>{c.count}건</td></tr>)}</tbody></table></div></div></section> }
function DataTable({ rows, allRows, setRows, fields, labels, query, setQuery, reset, placeholder, moneyFields=[] }){ return <section className="panel"><div className="toolbar"><label><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={placeholder}/></label><button className="danger" onClick={()=>{ if(confirm('샘플 데이터로 초기화할까요?')) reset(); }}><Trash2 size={16}/> Reset</button></div><div className="tableWrap"><table><thead><tr>{fields.map(f=><th key={f}>{labels[f]}</th>)}<th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}>{fields.map(f=><td key={f}>{moneyFields.includes(f) ? Number(r[f]||0).toLocaleString() : r[f]}</td>)}<td><button className="mini" onClick={()=>setRows(allRows.filter(x=>x.id!==r.id))}>삭제</button></td></tr>)}</tbody></table></div></section>; }
function RecordForm({ fields, labels, form, setForm, submit, required }){ return <section className="panel"><form className="form" onSubmit={submit}>{fields.map(f=><label key={f}>{labels[f]}<input value={form[f] ?? ''} onChange={e=>setForm({...form,[f]:e.target.value})} required={required.includes(f)} /></label>)}<button className="primary"><PlusCircle size={18}/> 등록하기</button></form></section>; }
function UploadPanel({ type, onUpload, result, desc }){ return <section className="panel upload"><Upload size={48}/><h3>엑셀 파일 업로드</h3><p>{desc}</p><input type="file" accept=".xlsx,.xls,.csv" onChange={e=>onUpload(e,type)}/>{result && result.type===type && <div className="result"><CheckCircle2/> 전체 {result.total}건 / 신규 {result.inserted}건 / 중복 제외 {result.duplicated}건</div>}<div className="notice"><AlertTriangle/> 원본 컬럼은 유지하고 Normalized KRW / FX Rate 컬럼을 추가해 비교 기준을 통일했습니다.</div></section>; }

export default App;
