import React, { useMemo, useState } from 'react';
import * as XLSX from 'xlsx';
import { BarChart, Bar, LineChart, PieChart, Pie, Cell, XAxis, YAxis, Tooltip, ResponsiveContainer, Legend, ComposedChart } from 'recharts';
import { LayoutDashboard, Table2, PlusCircle, Upload, Search, AlertTriangle, CheckCircle2, Trash2, Download, Plane, Globe2, Filter, Users, Bell, LogOut, Lock, FileText, Wand2, Save } from 'lucide-react';

const PAYMENT_KEY = 'sirva-payment-dashboard-records-v3';
const FLIGHT_KEY = 'sirva-flight-booking-records-v3';
const ACCOUNT_KEY = 'global-mobility-accounts-v1';
const NOTICE_KEY = 'global-mobility-notices-v1';
const SESSION_KEY = 'global-mobility-session-v1';
const FX = { KRW: 1, USD: 1350, SGD: 1000, TWD: 42, JPY: 9.2, AUD: 890 };
const COLORS = ['#4285f4', '#f9ab00', '#ea4335', '#34a853', '#7b61ff', '#00a3ff'];
const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const monthOptions = ['All', ...months];
const periodOptions = [
  { label:'2026 전체', start:'2026-01-01', end:'2026-12-31' },
  { label:'1분기', start:'2026-01-01', end:'2026-03-31' },
  { label:'2분기', start:'2026-04-01', end:'2026-06-30' },
  { label:'3분기', start:'2026-07-01', end:'2026-09-30' },
  { label:'4분기', start:'2026-10-01', end:'2026-12-31' }
];

const sampleRows = [
  ['Taiwan','Jan','2026-01-12','872156','217761','RFC','CP26773','Ranjan Tukesh','SIRVA Fee','Expat-Relovc','CP26773_Tukesh Ranjan_INV217761_260312','A70001131','USD',987,'2026-05-11','PO312440','100003884','N60','PAID'],
  ['Singapore','May','2026-05-14','875991','218455','CPSG','CP271555','Sam Bae','Disbursement','Expat-Tuition','CP271555_Sam Bae_INV218455_260514','SG100200','SGD',18900,'2026-06-20','PO318888','100006112','N30','PAID'],
  ['Korea','Jun','2026-06-02','879210','219001','CPKR','CP269477','Tracy Lu','SIRVA Fee','Expat-Relovc','CP269477_Tracy Lu_INV219001_260602','KR220100','USD',1450,'2026-06-30','PO320101','100006541','N60','PAYMENT_PENDING'],
  ['Japan','Oct','2026-10-10','889904','220771','CPJP','CP226805','Deepak Malani','Disbursement','Expat-Tuition','CP226805_Deepak Malani_INV220771_261010','JP700011','JPY',1650000,'2026-10-30','PO360120','100008551','N30','RECEIVED']
].map((r,i)=>({ id:`p${i+1}`, country:r[0], invoiceMonth:r[1], invoiceDate:r[2], fileNumber:r[3], invoiceNo:r[4], entity:r[5], employeeId:r[6], employeeName:r[7], serviceType:r[8], category:r[9], description:r[10], costCenter:r[11], currency:r[12], amount:r[13], paymentDate:r[14], poNumber:r[15], iacDocNo:r[16], paymentItem:r[17], status:r[18] }));

const sampleFlights = [
  ['Singapore','2026-07-08','HLF','CP269477','Tracy Lu','N','Coupang, Corp.','Brandon','SANKARAN/SANDHYA MS','Spouse','2026-08-12','','ICN','SIN','KRW',1784000,69200,'XXXXXXXXXXXX2880','','CP269477_Tracy Lu(S)','A7032610','BOOKED'],
  ['Taiwan','2026-08-14','Repat','CP271555','Sam Bae','N','Coupang, Corp.','Mathilde','BAE/SAM MR','Employee','2026-08-31','','ICN','TPE','KRW',814800,31400,'XXXXXXXXXXXX2880','','CP271555_Sam Bae(E)','A70108000','BOOKED'],
  ['Japan','2026-06-12','STA','CP256211','Jatin Chaudhary','N','Coupang, Corp.','Grace','CHAUDHARY/PRIYA JATIN MS','Spouse','2026-06-17','2026-08-15','ICN','NRT','KRW',1526000,58700,'XXXXXXXXXXXX2880','','CP256211_Jatin Chaudhary(S)','A1031019','BOOKED']
].map((r,i)=>({ id:`f${i+1}`, country:r[0], bookingDate:r[1], category:r[2], employeeId:r[3], employeeName:r[4], pil:r[5], entity:r[6], caseManager:r[7], passengerName:r[8], relationship:r[9], departureDate1:r[10], departureDate2:r[11], departure1:r[12], departure2:r[13], currency:r[14], airfare:r[15], trxFee:r[16], card:r[17], remark:r[18], iaccDetail:r[19], costCenter:r[20], status:r[21] }));

const defaultAccounts = [
  { id:'u1', name:'Admin', email:'admin@coupang.com', role:'Master Admin', department:'Global Mobility', status:'Active', password:'admin123', createdAt:'2026-01-01' },
  { id:'u2', name:'Finance Manager', email:'finance@coupang.com', role:'Finance', department:'Finance', status:'Active', password:'finance123', createdAt:'2026-02-01' },
  { id:'u3', name:'HR Operator', email:'hr@coupang.com', role:'HR Operator', department:'HR', status:'Active', password:'hr123', createdAt:'2026-03-01' }
];
const defaultNotices = [
  { id:'n1', title:'2026년 2분기 비용 데이터 검토 안내', category:'업무공지', body:'학비 및 항공권 비용 입력 시 국가, 통화, Normalized KRW 항목을 반드시 확인해주세요.', pinned:true, writer:'Admin', createdAt:'2026-04-01' },
  { id:'n2', title:'AI 인보이스 추출 메뉴 추가', category:'업데이트', body:'서로 다른 양식의 인보이스를 붙여넣거나 업로드한 뒤 AI 추출 결과를 검수하여 Payment 데이터로 저장할 수 있습니다.', pinned:false, writer:'Admin', createdAt:'2026-05-31' }
];

const paymentFields = ['country','invoiceMonth','invoiceDate','fileNumber','invoiceNo','entity','employeeId','employeeName','serviceType','category','description','costCenter','currency','amount','normalizedKrw','exchangeRate','paymentDate','poNumber','iacDocNo','paymentItem','status'];
const paymentLabels = { country:'Country', invoiceMonth:'Invoice Month', invoiceDate:'Invoice Date', fileNumber:'File Number', invoiceNo:'Invoice No', entity:'Entity', employeeId:'Employee ID', employeeName:'Employee Name', serviceType:'Service Type', category:'Category', description:'Text Description', costCenter:'Cost Center', currency:'Currency', amount:'Original Amount', normalizedKrw:'Normalized KRW', exchangeRate:'FX Rate', paymentDate:'Payment Date', poNumber:'PO', iacDocNo:'IAC Doc #', paymentItem:'PO Payment Item', status:'Status' };
const flightFields = ['country','bookingDate','category','employeeId','employeeName','pil','entity','caseManager','passengerName','relationship','departureDate1','departureDate2','departure1','departure2','currency','airfare','trxFee','normalizedKrw','exchangeRate','card','remark','iaccDetail','costCenter','status'];
const flightLabels = { country:'Country', bookingDate:'Booking Date', category:'Category', employeeId:'EE ID', employeeName:'Employee Name', pil:'PIL', entity:'Entity', caseManager:'Case Manager', passengerName:'Passenger Name', relationship:'Relationship', departureDate1:'Departure Date 1', departureDate2:'Departure Date 2', departure1:'Departure 1', departure2:'Departure 2', currency:'Currency', airfare:'Airfare', trxFee:'TRX Fee', normalizedKrw:'Normalized KRW', exchangeRate:'FX Rate', card:'CARD', remark:'Remark', iaccDetail:'iACC Detail', costCenter:'Cost Center', status:'Status' };
const aiFields = ['country','invoiceMonth','invoiceDate','invoiceNo','employeeId','employeeName','entity','category','description','currency','amount','paymentDate','costCenter','status'];

function load(key, fallback){ try { return JSON.parse(localStorage.getItem(key)) || fallback; } catch { return fallback; } }
function save(key, rows){ localStorage.setItem(key, JSON.stringify(rows)); }
function num(v){ return Number(String(v ?? 0).replace(/[₩$,]/g,'')) || 0; }
function fx(currency){ return FX[String(currency || 'KRW').toUpperCase()] || 1; }
function krw(v, currency='KRW'){ return Math.round(num(v) * fx(currency)); }
function paymentKrw(r){ return r.normalizedKrw ? num(r.normalizedKrw) : krw(r.amount, r.currency || 'USD'); }
function flightKrw(r){ return r.normalizedKrw ? num(r.normalizedKrw) : krw(num(r.airfare)+num(r.trxFee), r.currency || 'KRW'); }
function ymd(d){ return String(d || '').slice(0,10); }
function inRange(date, start, end){ const d = ymd(date); return (!start || d >= start) && (!end || d <= end); }
function monthFromDate(d){ const m = new Date(d).getMonth(); return Number.isFinite(m) && m >= 0 ? months[m] : 'Unknown'; }
function getRaw(raw, ...names){ for (const n of names){ const k = Object.keys(raw).find(x => x.trim().toLowerCase() === n.toLowerCase()); if(k) return raw[k]; } return ''; }
function paymentDupKey(r){ return [r.invoiceNo, r.employeeId, r.fileNumber, r.amount].map(v=>String(v||'').trim().toLowerCase()).join('|'); }
function flightDupKey(r){ return [r.bookingDate, r.employeeId, r.passengerName, r.departureDate1, r.departure1, r.departure2, r.airfare].map(v=>String(v||'').trim().toLowerCase()).join('|'); }
function makeExcelDate(v){ if(typeof v === 'number'){ const d = XLSX.SSF.parse_date_code(v); if(d) return `${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`; } return String(v || ''); }
function inferCountryFromRoute(code){ const c = String(code || '').toUpperCase(); const map = { ICN:'Korea', GMP:'Korea', PUS:'Korea', SIN:'Singapore', TPE:'Taiwan', TYO:'Japan', NRT:'Japan', HND:'Japan' }; return map[c] || 'Unknown'; }
function flightCountry(r){ return r.country || inferCountryFromRoute(r.departure2) || inferCountryFromRoute(r.departure1) || 'Unknown'; }
function normalizePaymentRow(r){ const currency = r.currency || 'USD'; return { ...r, currency, exchangeRate:r.exchangeRate || fx(currency), normalizedKrw: r.normalizedKrw || paymentKrw({...r,currency}) }; }
function normalizeFlightRow(r){ const currency = r.currency || 'KRW'; return { ...r, country:r.country || flightCountry(r), currency, exchangeRate:r.exchangeRate || fx(currency), normalizedKrw: r.normalizedKrw || flightKrw({...r,currency}) }; }
function normalizePayment(raw){ const currency=getRaw(raw,'Currency') || 'USD'; const amount=num(getRaw(raw,'Amount','USD','Invoice Amount','Total Amount','Payment Amount')); return normalizePaymentRow({ id:crypto.randomUUID(), country:getRaw(raw,'Country') || 'Unknown', invoiceMonth:getRaw(raw,'Invoice Month','Month') || monthFromDate(getRaw(raw,'Invoice Date','Invoice date')), invoiceDate:makeExcelDate(getRaw(raw,'Invoice Date','Invoice date')), fileNumber:getRaw(raw,'File Number','File Num','File No') || '', invoiceNo:getRaw(raw,'Invoice No','Invoice Number','Invoice No.') || '', entity:getRaw(raw,'Entity') || '', employeeId:getRaw(raw,'Employee ID','Employee','EE ID') || '', employeeName:getRaw(raw,'Employee Name') || '', serviceType:getRaw(raw,'Service Type') || '', category:getRaw(raw,'Category','Item','Item Details') || '', description:getRaw(raw,'Text Description','Description') || '', costCenter:getRaw(raw,'Cost Center') || '', currency, amount, paymentDate:makeExcelDate(getRaw(raw,'Payment Date')), poNumber:getRaw(raw,'PO','PO Number') || '', iacDocNo:getRaw(raw,'IAC Doc #','IAC Doc') || '', paymentItem:getRaw(raw,'PO Payment Item','Payment Item') || '', status:getRaw(raw,'Status') || 'RECEIVED' }); }
function normalizeFlight(raw){ const departure2 = getRaw(raw,'Departure 2') || ''; const currency = getRaw(raw,'Currency') || 'KRW'; return normalizeFlightRow({ id:crypto.randomUUID(), country:getRaw(raw,'Country') || inferCountryFromRoute(departure2), bookingDate:makeExcelDate(getRaw(raw,'Booking Date')), category:getRaw(raw,'Category') || '', employeeId:getRaw(raw,'EE ID','Employee ID') || '', employeeName:getRaw(raw,'Employee Name') || '', pil:getRaw(raw,'PIL') || '', entity:getRaw(raw,'Entity') || '', caseManager:getRaw(raw,'Case Manager') || '', passengerName:getRaw(raw,'Passenger Name') || '', relationship:getRaw(raw,'Relationship') || '', departureDate1:makeExcelDate(getRaw(raw,'Departure Date 1','Departure Date')), departureDate2:makeExcelDate(getRaw(raw,'Departure Date 2')), departure1:getRaw(raw,'Departure 1','Departure') || '', departure2, currency, airfare:num(getRaw(raw,'Airfare')), trxFee:num(getRaw(raw,'TRX Fee')), card:getRaw(raw,'CARD') || '', remark:getRaw(raw,'Remark') || '', iaccDetail:getRaw(raw,'iACC Detail') || '', costCenter:getRaw(raw,'Cost Center') || '', status:getRaw(raw,'Status') || 'BOOKED' }); }
function detect(patterns, text, fallback=''){ for(const p of patterns){ const m = text.match(p); if(m?.[1]) return m[1].trim(); } return fallback; }
function mockAiExtract(text, fileName=''){ const t = String(text || ''); const invoiceDate = detect([/invoice\s*date[:\s]+(\d{4}[-/.]\d{1,2}[-/.]\d{1,2})/i,/date[:\s]+(\d{4}[-/.]\d{1,2}[-/.]\d{1,2})/i], t, '2026-05-31').replaceAll('/','-').replaceAll('.','-'); const currency = detect([/\b(USD|KRW|SGD|TWD|JPY|AUD)\b/i], t, 'USD').toUpperCase(); const amount = num(detect([/(?:total|amount due|balance|tuition fee)[:\s]+(?:USD|KRW|SGD|TWD|JPY|AUD|₩|\$)?\s*([\d,]+(?:\.\d+)?)/i,/(?:USD|KRW|SGD|TWD|JPY|AUD|₩|\$)\s*([\d,]+(?:\.\d+)?)/i], t, '4500')); const country = detect([/country[:\s]+([A-Za-z ]+)/i], t, currency==='SGD'?'Singapore':currency==='JPY'?'Japan':currency==='TWD'?'Taiwan':'Korea'); return normalizePaymentRow({ id:crypto.randomUUID(), country, invoiceMonth:monthFromDate(invoiceDate), invoiceDate, fileNumber:fileName || `AI-${Date.now()}`, invoiceNo:detect([/invoice\s*(?:no|number|#)[:\s-]+([A-Z0-9-]+)/i,/inv[:\s-]+([A-Z0-9-]+)/i], t, `AI-${String(Date.now()).slice(-6)}`), entity:detect([/entity[:\s]+([A-Z0-9]+)/i], t, 'CPGM'), employeeId:detect([/(?:employee|ee)\s*(?:id)?[:\s]+(CP\d+)/i], t, 'CP000000'), employeeName:detect([/employee\s*name[:\s]+([^\n]+)/i,/parent[:\s]+([^\n]+)/i], t, 'Need Review'), serviceType:'Disbursement', category:detect([/category[:\s]+([^\n]+)/i], t, 'Expat-Tuition'), description:detect([/school[:\s]+([^\n]+)/i,/institution[:\s]+([^\n]+)/i], t, 'AI extracted tuition invoice'), costCenter:detect([/cost\s*center[:\s]+([A-Z0-9-]+)/i], t, ''), currency, amount, paymentDate:detect([/(?:due date|payment date)[:\s]+(\d{4}[-/.]\d{1,2}[-/.]\d{1,2})/i], t, '').replaceAll('/','-').replaceAll('.','-'), poNumber:'', iacDocNo:'', paymentItem:'', status:'AI_REVIEW' }); }
function confidence(field, value){ if(!value) return 42; if(['invoiceNo','amount','currency','invoiceDate'].includes(field)) return 92; if(['employeeName','description','paymentDate'].includes(field)) return 78; return 84; }

function FilterBar({ filters, setFilters, countries, categories }){ return <div className="filterBar"><div><Filter size={16}/><b>Filter</b></div><label>기간<select value={filters.period} onChange={e=>setFilters({...filters,period:e.target.value})}>{periodOptions.map(p=><option key={p.label}>{p.label}</option>)}</select></label><label>월<select value={filters.month} onChange={e=>setFilters({...filters,month:e.target.value})}>{monthOptions.map(m=><option key={m}>{m}</option>)}</select></label><label>국가<select value={filters.country} onChange={e=>setFilters({...filters,country:e.target.value})}><option>All</option>{countries.map(c=><option key={c}>{c}</option>)}</select></label><label>구분<select value={filters.costType} onChange={e=>setFilters({...filters,costType:e.target.value})}><option>All</option><option>Tuition</option><option>Flight</option></select></label><label>카테고리<select value={filters.category} onChange={e=>setFilters({...filters,category:e.target.value})}><option>All</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label></div> }

function App(){
  const [accounts, setAccounts] = useState(()=>load(ACCOUNT_KEY, defaultAccounts));
  const [session, setSession] = useState(()=>load(SESSION_KEY, null));
  const [payments, setPayments] = useState(()=>load(PAYMENT_KEY, sampleRows).map(normalizePaymentRow));
  const [flights, setFlights] = useState(()=>load(FLIGHT_KEY, sampleFlights).map(normalizeFlightRow));
  const [notices, setNotices] = useState(()=>load(NOTICE_KEY, defaultNotices));
  const [view, setView] = useState('overviewDashboard');
  const [query, setQuery] = useState('');
  const [uploadResult, setUploadResult] = useState(null);
  const [filters, setFilters] = useState({ period:'2026 전체', month:'All', country:'All', costType:'All', category:'All' });
  const [paymentForm, setPaymentForm] = useState({ country:'Taiwan', invoiceMonth:'Apr', invoiceDate:'2026-04-02', fileNumber:'', invoiceNo:'', entity:'CPTW', employeeId:'', employeeName:'', serviceType:'SIRVA Fee', category:'Expat-Relovc', description:'', costCenter:'', currency:'USD', amount:'', normalizedKrw:'', exchangeRate:'1350', paymentDate:'', poNumber:'', iacDocNo:'', paymentItem:'', status:'RECEIVED' });
  const [flightForm, setFlightForm] = useState({ country:'', bookingDate:'2026-05-06', category:'HLF', employeeId:'', employeeName:'', pil:'N', entity:'Coupang, Corp.', caseManager:'', passengerName:'', relationship:'Employee', departureDate1:'', departureDate2:'', departure1:'ICN', departure2:'', currency:'KRW', airfare:'', trxFee:'', normalizedKrw:'', exchangeRate:'1', card:'XXXXXXXXXXXX2880', remark:'', iaccDetail:'', costCenter:'', status:'BOOKED' });
  const [aiSource, setAiSource] = useState('School: Seoul International School\nInvoice No: SIS-2026-0531\nInvoice Date: 2026-05-31\nDue Date: 2026-06-15\nEmployee ID: CP269477\nEmployee Name: Tracy Lu\nCountry: Korea\nCategory: Expat-Tuition\nTotal: USD 4,500');
  const [aiRecord, setAiRecord] = useState(null);
  const [aiFileName, setAiFileName] = useState('');

  const saveAccounts = next => { setAccounts(next); save(ACCOUNT_KEY, next); };
  const saveNotices = next => { setNotices(next); save(NOTICE_KEY, next); };
  const setPaymentSave = next => { const n = next.map(normalizePaymentRow); setPayments(n); save(PAYMENT_KEY, n); };
  const setFlightSave = next => { const n = next.map(normalizeFlightRow); setFlights(n); save(FLIGHT_KEY, n); };
  function login(email, password){ const user = accounts.find(a => a.email.toLowerCase() === email.toLowerCase() && a.password === password && a.status === 'Active'); if(!user) return false; const safe = { id:user.id, name:user.name, email:user.email, role:user.role, department:user.department }; setSession(safe); save(SESSION_KEY, safe); return true; }
  function logout(){ setSession(null); localStorage.removeItem(SESSION_KEY); }

  const period = periodOptions.find(p=>p.label===filters.period) || periodOptions[0];
  const filteredPaymentBase = payments.filter(r => inRange(r.invoiceDate || r.paymentDate, period.start, period.end) && (filters.month==='All' || r.invoiceMonth===filters.month) && (filters.country==='All' || r.country===filters.country) && (filters.category==='All' || r.category===filters.category));
  const filteredFlightBase = flights.filter(r => inRange(r.bookingDate, period.start, period.end) && (filters.month==='All' || monthFromDate(r.bookingDate)===filters.month) && (filters.country==='All' || flightCountry(r)===filters.country) && (filters.category==='All' || r.category===filters.category));
  const countries = [...new Set([...payments.map(r=>r.country || 'Unknown'), ...flights.map(flightCountry)])].sort();
  const categories = [...new Set([...payments.map(r=>r.category || 'Unknown'), ...flights.map(r=>r.category || 'Unknown')])].sort();
  const overviewStats = useMemo(()=>{ const pay = filters.costType==='Flight' ? [] : filteredPaymentBase; const flt = filters.costType==='Tuition' ? [] : filteredFlightBase; const tuitionAnnual = pay.reduce((s,r)=>s+paymentKrw(r),0); const flightAnnual = flt.reduce((s,r)=>s+flightKrw(r),0); const byMonth = months.map(month => ({ month, Tuition:pay.filter(r=>r.invoiceMonth===month).reduce((s,r)=>s+paymentKrw(r),0), Flight:flt.filter(r=>monthFromDate(r.bookingDate)===month).reduce((s,r)=>s+flightKrw(r),0) })).map(m=>({...m, Total:m.Tuition+m.Flight})); const byCountry = [...new Set([...pay.map(r=>r.country || 'Unknown'), ...flt.map(flightCountry)])].map(country => { const tuition = pay.filter(r=>(r.country || 'Unknown')===country).reduce((s,r)=>s+paymentKrw(r),0); const flight = flt.filter(r=>flightCountry(r)===country).reduce((s,r)=>s+flightKrw(r),0); return { country, tuition, flight, total:tuition+flight, tuitionCount:pay.filter(r=>(r.country || 'Unknown')===country).length, flightCount:flt.filter(r=>flightCountry(r)===country).length }; }).sort((a,b)=>b.total-a.total); const topMonth = byMonth.reduce((max,m)=>m.Total > max.Total ? m : max, { month:'-', Total:0 }); return { tuitionAnnual, flightAnnual, grandTotal:tuitionAnnual+flightAnnual, byCountry, byMonth, topMonth }; },[filteredPaymentBase, filteredFlightBase, filters.costType]);
  const payStats = useMemo(()=>{ const data = filteredPaymentBase; const total = data.reduce((s,r)=>s+paymentKrw(r),0); const sirva = data.filter(r=>String(r.serviceType).toLowerCase().includes('sirva')).reduce((s,r)=>s+paymentKrw(r),0); const disb = data.filter(r=>String(r.serviceType).toLowerCase().includes('disbur')).reduce((s,r)=>s+paymentKrw(r),0); const byMonth = months.map(m=>({ month:m, SIRVA:data.filter(r=>r.invoiceMonth===m && String(r.serviceType).toLowerCase().includes('sirva')).reduce((s,r)=>s+paymentKrw(r),0), Disbursement:data.filter(r=>r.invoiceMonth===m && String(r.serviceType).toLowerCase().includes('disbur')).reduce((s,r)=>s+paymentKrw(r),0)})); const byCountry = [...new Set(data.map(r=>r.country || 'Unknown'))].map(c=>({ country:c, total:data.filter(r=>r.country===c).reduce((s,r)=>s+paymentKrw(r),0), sirva:data.filter(r=>r.country===c && String(r.serviceType).toLowerCase().includes('sirva')).reduce((s,r)=>s+paymentKrw(r),0), disbursement:data.filter(r=>r.country===c && String(r.serviceType).toLowerCase().includes('disbur')).reduce((s,r)=>s+paymentKrw(r),0)})); return { total, sirva, disb, byMonth, byCountry }; },[filteredPaymentBase]);
  const flightStats = useMemo(()=>{ const data = filteredFlightBase; const totalAirfare = data.reduce((s,r)=>s+krw(r.airfare,r.currency),0); const totalTrx = data.reduce((s,r)=>s+krw(r.trxFee,r.currency),0); const byMonth = months.map(m=>({ month:m, Airfare:data.filter(r=>monthFromDate(r.bookingDate)===m).reduce((s,r)=>s+krw(r.airfare,r.currency),0), TRX:data.filter(r=>monthFromDate(r.bookingDate)===m).reduce((s,r)=>s+krw(r.trxFee,r.currency),0) })); const byCategory = [...new Set(data.map(r=>r.category || 'Unknown'))].map(category=>({ category, amount:data.filter(r=>(r.category||'Unknown')===category).reduce((s,r)=>s+flightKrw(r),0), count:data.filter(r=>(r.category||'Unknown')===category).length })); const byRelation = [...new Set(data.map(r=>r.relationship || 'Unknown'))].map(name=>({ name, value:data.filter(r=>(r.relationship||'Unknown')===name).length })); return { totalAirfare, totalTrx, pax:data.length, employees:new Set(data.map(r=>r.employeeId).filter(Boolean)).size, byMonth, byCategory, byRelation }; },[filteredFlightBase]);

  const isFlight = view.startsWith('flight'); const isOverview = view==='overviewDashboard'; const isAi = view==='invoiceAi';
  const titleMap = { overviewDashboard:'통합 비용 대시보드', paymentDashboard:'학비/교육비 대시보드', paymentTable:'Payment Tracker', paymentForm:'Payment 개별 등록', paymentUpload:'Payment Excel Upload', invoiceAi:'AI 인보이스 추출/검수', flightDashboard:'항공권 대시보드', flightTable:'항공권 데이터 관리', flightForm:'항공권 개별 등록', flightUpload:'항공권 Excel Upload', accounts:'계정관리', notices:'공지사항' };
  const headerSub = isAi?'Invoice OCR + AI Review Workflow':isOverview?'Normalized KRW / Integrated Cost View':isFlight?'Flight Booking / Airfare Cost':view==='accounts'?'User Access / Role Management':view==='notices'?'Notice Board / Internal Announcement':'Global Mobility Tuition / Education Cost';
  const filteredPayments = payments.filter(r => JSON.stringify(r).toLowerCase().includes(query.toLowerCase()));
  const filteredFlights = flights.filter(r => JSON.stringify(r).toLowerCase().includes(query.toLowerCase()));
  function addPayment(e){ e.preventDefault(); const record=normalizePaymentRow({...paymentForm,id:crypto.randomUUID(),amount:num(paymentForm.amount),normalizedKrw:paymentForm.normalizedKrw?num(paymentForm.normalizedKrw):'',exchangeRate:paymentForm.exchangeRate||fx(paymentForm.currency)}); if(payments.some(r=>paymentDupKey(r)===paymentDupKey(record))) return alert('중복 Payment 데이터입니다.'); setPaymentSave([record,...payments]); setView('paymentTable'); }
  function addFlight(e){ e.preventDefault(); const record=normalizeFlightRow({...flightForm,id:crypto.randomUUID(),country:flightForm.country || inferCountryFromRoute(flightForm.departure2),airfare:num(flightForm.airfare),trxFee:num(flightForm.trxFee)}); if(flights.some(r=>flightDupKey(r)===flightDupKey(record))) return alert('중복 항공권 데이터입니다.'); setFlightSave([record,...flights]); setView('flightTable'); }
  async function onUpload(e, type){ const file=e.target.files?.[0]; if(!file) return; const data=await file.arrayBuffer(); const wb=XLSX.read(data); const json=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]], { defval:'' }); if(type==='flight'){ const incoming=json.map(normalizeFlight).filter(r=>r.employeeId || r.passengerName || r.bookingDate); const keys=new Set(flights.map(flightDupKey)); const fresh=incoming.filter(r=>!keys.has(flightDupKey(r))); setFlightSave([...fresh,...flights]); setUploadResult({type,total:incoming.length,inserted:fresh.length,duplicated:incoming.length-fresh.length}); } else { const incoming=json.map(normalizePayment).filter(r=>r.invoiceNo || r.fileNumber || r.employeeId); const keys=new Set(payments.map(paymentDupKey)); const fresh=incoming.filter(r=>!keys.has(paymentDupKey(r))); setPaymentSave([...fresh,...payments]); setUploadResult({type,total:incoming.length,inserted:fresh.length,duplicated:incoming.length-fresh.length}); } e.target.value=''; }
  function exportExcel(){ const fields = isOverview ? ['country','tuition','flight','total','tuitionCount','flightCount'] : isFlight ? flightFields : paymentFields; const labels = isOverview ? {country:'Country',tuition:'Tuition KRW',flight:'Flight KRW',total:'Total KRW',tuitionCount:'Tuition Count',flightCount:'Flight Count'} : isFlight ? flightLabels : paymentLabels; const data = isOverview ? overviewStats.byCountry : isFlight ? flights : payments; const ws=XLSX.utils.json_to_sheet(data.map(r=>Object.fromEntries(fields.map(f=>[labels[f], r[f]])))); const wb=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb,ws,isOverview?'Integrated':isFlight?'Flight':'Payment'); XLSX.writeFile(wb,isOverview?'integrated-cost-dashboard.xlsx':isFlight?'flight-booking-data.xlsx':'sirva-payment-tracker.xlsx'); }
  async function onAiFile(e){ const file=e.target.files?.[0]; if(!file) return; setAiFileName(file.name); if(/\.(txt|csv)$/i.test(file.name)){ setAiSource(await file.text()); } else { setAiSource(`Uploaded file: ${file.name}\nSchool: Sample International School\nInvoice No: AUTO-${Date.now()}\nInvoice Date: 2026-05-31\nDue Date: 2026-06-15\nEmployee ID: CP000000\nEmployee Name: Need Review\nTotal: USD 4500`); } }
  function runAi(){ setAiRecord(mockAiExtract(aiSource, aiFileName)); }
  function saveAiRecord(){ if(!aiRecord) return; const record = normalizePaymentRow({...aiRecord, id:crypto.randomUUID(), status:'RECEIVED'}); if(payments.some(r=>paymentDupKey(r)===paymentDupKey(record))) return alert('중복 가능성이 있는 인보이스입니다. Invoice No / Employee ID / Amount를 확인해주세요.'); setPaymentSave([record,...payments]); setAiRecord(null); setView('paymentTable'); }
  if(!session) return <LoginPage onLogin={login}/>;
  return <div className="app"><aside className="side"><h1><span>C</span> Global<br/>Mobility</h1><div className="loginMeta"><b>{session.name}</b><small>{session.role}</small></div><button onClick={()=>setView('overviewDashboard')} className={view==='overviewDashboard'?'active':''}><Globe2/> 통합 대시보드</button><div className="sideGroup">Tuition / Payment</div><button onClick={()=>setView('paymentDashboard')} className={view==='paymentDashboard'?'active':''}><LayoutDashboard/> Payment 대시보드</button><button onClick={()=>setView('paymentTable')} className={view==='paymentTable'?'active':''}><Table2/> Payment 데이터</button><button onClick={()=>setView('paymentForm')} className={view==='paymentForm'?'active':''}><PlusCircle/> Payment 등록</button><button onClick={()=>setView('paymentUpload')} className={view==='paymentUpload'?'active':''}><Upload/> Payment 업로드</button><button onClick={()=>setView('invoiceAi')} className={view==='invoiceAi'?'active':''}><FileText/> AI 인보이스 추출</button><div className="sideGroup">Flight Booking</div><button onClick={()=>setView('flightDashboard')} className={view==='flightDashboard'?'active':''}><Plane/> 항공권 대시보드</button><button onClick={()=>setView('flightTable')} className={view==='flightTable'?'active':''}><Table2/> 항공권 데이터</button><button onClick={()=>setView('flightForm')} className={view==='flightForm'?'active':''}><PlusCircle/> 항공권 등록</button><button onClick={()=>setView('flightUpload')} className={view==='flightUpload'?'active':''}><Upload/> 항공권 업로드</button><div className="sideGroup">Admin</div><button onClick={()=>setView('accounts')} className={view==='accounts'?'active':''}><Users/> 계정관리</button><button onClick={()=>setView('notices')} className={view==='notices'?'active':''}><Bell/> 공지사항</button><button onClick={logout}><LogOut/> 로그아웃</button></aside><main><header><div><p>{headerSub}</p><h2>{titleMap[view]}</h2></div>{!['accounts','notices','invoiceAi'].includes(view) && <button className="ghost" onClick={exportExcel}><Download size={16}/> Export Excel</button>}</header>
    {(view.includes('Dashboard')) && <FilterBar filters={filters} setFilters={setFilters} countries={countries} categories={categories}/>} 
    {view==='overviewDashboard' && <Overview stats={overviewStats}/>} {view==='paymentDashboard' && <PaymentDash stats={payStats}/>} {view==='flightDashboard' && <FlightDash stats={flightStats}/>} 
    {view==='paymentTable' && <DataTable rows={filteredPayments} allRows={payments} setRows={setPaymentSave} fields={paymentFields} labels={paymentLabels} query={query} setQuery={setQuery} reset={()=>setPaymentSave(sampleRows)} placeholder="국가, 직원명, Invoice No, PO 검색" moneyFields={['amount','normalizedKrw','exchangeRate']} />}
    {view==='flightTable' && <DataTable rows={filteredFlights} allRows={flights} setRows={setFlightSave} fields={flightFields} labels={flightLabels} query={query} setQuery={setQuery} reset={()=>setFlightSave(sampleFlights)} placeholder="국가, 직원명, 탑승객, 항공구간, Cost Center 검색" moneyFields={['airfare','trxFee','normalizedKrw','exchangeRate']} />}
    {view==='paymentForm' && <RecordForm fields={paymentFields} labels={paymentLabels} form={paymentForm} setForm={setPaymentForm} submit={addPayment} required={['invoiceNo','employeeId','amount']} />}
    {view==='flightForm' && <RecordForm fields={flightFields} labels={flightLabels} form={flightForm} setForm={setFlightForm} submit={addFlight} required={['bookingDate','employeeId','passengerName','airfare']} />}
    {view==='paymentUpload' && <UploadPanel type="payment" onUpload={onUpload} result={uploadResult} desc="Payment Tracker 엑셀 업로드: 원본 금액/통화는 보존하고, Normalized KRW를 별도 계산합니다." />}
    {view==='flightUpload' && <UploadPanel type="flight" onUpload={onUpload} result={uploadResult} desc="항공권 엑셀 업로드: Airfare + TRX Fee를 KRW 기준으로 정규화하고 중복을 제외합니다." />}
    {view==='invoiceAi' && <InvoiceAiPage source={aiSource} setSource={setAiSource} record={aiRecord} setRecord={setAiRecord} onFile={onAiFile} onRun={runAi} onSave={saveAiRecord}/>} 
    {view==='accounts' && <AccountsPage accounts={accounts} setAccounts={saveAccounts}/>} {view==='notices' && <NoticesPage notices={notices} setNotices={saveNotices} user={session}/>} 
  </main></div>;
}

function LoginPage({onLogin}){ const [email,setEmail]=useState('admin@coupang.com'); const [password,setPassword]=useState('admin123'); const [error,setError]=useState(''); function submit(e){ e.preventDefault(); if(!onLogin(email,password)) setError('계정 정보가 맞지 않거나 비활성 계정입니다.'); } return <div className="loginPage"><div className="loginCard"><div className="loginLogo">coupang</div><h1>Global Mobility</h1><p>학비·항공권 비용 관리를 위한 내부 대시보드</p><form onSubmit={submit}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} /></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} /></label>{error && <div className="loginError"><AlertTriangle size={16}/>{error}</div>}<button className="primary"><Lock size={16}/> 로그인</button></form><small>Demo: admin@coupang.com / admin123</small></div></div> }
function InvoiceAiPage({source,setSource,record,setRecord,onFile,onRun,onSave}){ const missing = record ? ['invoiceNo','employeeId','amount','currency','invoiceDate'].filter(f=>!record[f]) : []; return <section className="aiGrid"><div className="panel aiInput"><h3><FileText size={18}/> 인보이스 업로드/텍스트 입력</h3><p>현재 화면은 프론트 데모입니다. 실제 운영에서는 이 지점에서 백엔드가 OCR/AI API를 호출하고, 결과만 프론트로 전달합니다.</p><input type="file" accept=".pdf,.png,.jpg,.jpeg,.txt,.csv" onChange={onFile}/><textarea value={source} onChange={e=>setSource(e.target.value)} placeholder="인보이스 원문 또는 OCR 결과를 붙여넣으세요."/><button className="primary" onClick={onRun}><Wand2 size={18}/> AI 분석 실행</button></div><div className="panel aiReview"><h3><CheckCircle2 size={18}/> 추출 결과 검수</h3>{!record ? <div className="emptyState">왼쪽에서 인보이스를 업로드하거나 샘플 텍스트로 AI 분석을 실행하세요.</div> : <><div className="aiSummary"><span>검수 필요 {missing.length}건</span><span>예상 KRW ₩{paymentKrw(record).toLocaleString()}</span><span>중복 저장 방지 적용</span></div><form className="form aiForm">{aiFields.map(f=><label key={f}>{paymentLabels[f] || f}<small>신뢰도 {confidence(f, record[f])}%</small><input value={record[f] ?? ''} onChange={e=>setRecord({...record,[f]:e.target.value})}/></label>)}</form><div className="notice"><AlertTriangle/> 신뢰도 낮은 항목은 담당자가 수정한 뒤 확정 저장하세요. 저장 시 Payment 데이터에 바로 반영됩니다.</div><button className="primary" onClick={onSave}><Save size={18}/> 검수 완료 후 Payment 저장</button></>}</div></section>; }
function AccountsPage({accounts,setAccounts}){ const empty={name:'',email:'',role:'HR Operator',department:'Global Mobility',status:'Active',password:'1234'}; const [form,setForm]=useState(empty); function add(e){ e.preventDefault(); if(accounts.some(a=>a.email.toLowerCase()===form.email.toLowerCase())) return alert('이미 등록된 이메일입니다.'); setAccounts([{...form,id:crypto.randomUUID(),createdAt:new Date().toISOString().slice(0,10)},...accounts]); setForm(empty); } return <section className="adminGrid"><div className="panel"><h3>계정 등록</h3><form className="form adminForm" onSubmit={add}>{['name','email','role','department','status','password'].map(f=><label key={f}>{f}<input value={form[f]} onChange={e=>setForm({...form,[f]:e.target.value})} required /></label>)}<button className="primary"><PlusCircle size={16}/> 계정 추가</button></form></div><div className="panel"><h3>계정 목록</h3><div className="tableWrap short"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Dept</th><th>Status</th><th></th></tr></thead><tbody>{accounts.map(a=><tr key={a.id}><td>{a.name}</td><td>{a.email}</td><td>{a.role}</td><td>{a.department}</td><td>{a.status}</td><td><button className="mini" onClick={()=>setAccounts(accounts.map(x=>x.id===a.id?{...x,status:x.status==='Active'?'Inactive':'Active'}:x))}>상태변경</button><button className="mini" onClick={()=>setAccounts(accounts.filter(x=>x.id!==a.id))}>삭제</button></td></tr>)}</tbody></table></div></div></section> }
function NoticesPage({notices,setNotices,user}){ const empty={title:'',category:'업무공지',body:'',pinned:false}; const [form,setForm]=useState(empty); function add(e){ e.preventDefault(); setNotices([{...form,id:crypto.randomUUID(),writer:user.name,createdAt:new Date().toISOString().slice(0,10)},...notices]); setForm(empty); } const sorted=[...notices].sort((a,b)=>Number(b.pinned)-Number(a.pinned)||b.createdAt.localeCompare(a.createdAt)); return <section className="adminGrid"><div className="panel"><h3>공지 등록</h3><form className="form noticeForm" onSubmit={add}><label>제목<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required /></label><label>분류<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} /></label><label>상단 고정<input value={form.pinned?'Y':'N'} onChange={e=>setForm({...form,pinned:e.target.value.toUpperCase()==='Y'})} /></label><label className="full">내용<input value={form.body} onChange={e=>setForm({...form,body:e.target.value})} required /></label><button className="primary"><Bell size={16}/> 공지 등록</button></form></div><div className="noticeList">{sorted.map(n=><article className="noticeCard" key={n.id}><div><b>{n.pinned?'📌 ':''}{n.title}</b><small>{n.category} · {n.writer} · {n.createdAt}</small></div><p>{n.body}</p><button className="mini" onClick={()=>setNotices(notices.filter(x=>x.id!==n.id))}>삭제</button></article>)}</div></section> }
function Overview({stats}){ return <section className="dash"><div className="hero four"><div><span>Annual Usage Cost</span><strong>₩{stats.grandTotal.toLocaleString()}</strong><small>정규화 KRW 기준</small></div><div className="split"><b>Tuition / Education</b><strong>₩{stats.tuitionAnnual.toLocaleString()}</strong><small>FX normalized</small></div><div className="split orange"><b>Flight Booking</b><strong>₩{stats.flightAnnual.toLocaleString()}</strong><small>Airfare + TRX Fee</small></div><div className="split purple"><b>Monthly Peak</b><strong>{stats.topMonth.month}</strong><small>₩{stats.topMonth.Total.toLocaleString()}</small></div></div><div className="panel wide"><h3>월별 사용 비용</h3><ResponsiveContainer height={320}><ComposedChart data={stats.byMonth}><XAxis dataKey="month"/><YAxis/><Tooltip/><Legend/><Bar dataKey="Tuition" stackId="a" fill="#4285f4"/><Bar dataKey="Flight" stackId="a" fill="#f9ab00"/><LineChart/><Line type="monotone" dataKey="Total" stroke="#ea4335" strokeWidth={3}/></ComposedChart></ResponsiveContainer></div><div className="panel wide"><h3>국가별 학비/항공권 비용 비교</h3><ResponsiveContainer height={330}><BarChart data={stats.byCountry}><XAxis dataKey="country"/><YAxis/><Tooltip/><Legend/><Bar dataKey="tuition" name="Tuition" fill="#4285f4"/><Bar dataKey="flight" name="Flight" fill="#f9ab00"/></BarChart></ResponsiveContainer></div></section> }
function PaymentDash({stats}){ return <section className="dash"><div className="hero"><div><span>Tuition Spend</span><strong>₩{stats.total.toLocaleString()}</strong></div><div className="split"><b>SIRVA Fee</b><strong>₩{stats.sirva.toLocaleString()}</strong></div><div className="split orange"><b>Disbursement</b><strong>₩{stats.disb.toLocaleString()}</strong></div></div><div className="panel wide"><h3>월별 학비/교육비</h3><ResponsiveContainer height={300}><BarChart data={stats.byMonth}><XAxis dataKey="month"/><YAxis/><Tooltip/><Legend/><Bar dataKey="SIRVA" stackId="a" fill="#4285f4"/><Bar dataKey="Disbursement" stackId="a" fill="#f9ab00"/></BarChart></ResponsiveContainer></div><div className="grid3">{stats.byCountry.map(c=><div className="country" key={c.country}><h3>{c.country}</h3><strong>₩{c.total.toLocaleString()}</strong><ResponsiveContainer height={130}><PieChart><Pie data={[{name:'SIRVA Fee',value:c.sirva},{name:'Disbursement',value:c.disbursement}]} dataKey="value" innerRadius={34} outerRadius={55}>{[0,1].map(i=><Cell key={i} fill={COLORS[i]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div>)}</div></section> }
function FlightDash({stats}){ return <section className="dash"><div className="hero four"><div><span>Total Flight Cost</span><strong>₩{(stats.totalAirfare+stats.totalTrx).toLocaleString()}</strong></div><div className="split"><b>Airfare</b><strong>₩{stats.totalAirfare.toLocaleString()}</strong></div><div className="split orange"><b>TRX Fee</b><strong>₩{stats.totalTrx.toLocaleString()}</strong></div><div className="split purple"><b>Passengers</b><strong>{stats.pax.toLocaleString()}</strong><small>{stats.employees} employees</small></div></div><div className="panel wide"><h3>월별 항공권 비용</h3><ResponsiveContainer height={300}><BarChart data={stats.byMonth}><XAxis dataKey="month"/><YAxis/><Tooltip/><Legend/><Bar dataKey="Airfare" stackId="a" fill="#4285f4"/><Bar dataKey="TRX" stackId="a" fill="#f9ab00"/></BarChart></ResponsiveContainer></div><div className="grid3"><div className="country"><h3>Relationship</h3><ResponsiveContainer height={170}><PieChart><Pie data={stats.byRelation} dataKey="value" nameKey="name" innerRadius={42} outerRadius={68}>{stats.byRelation.map((_,i)=><Cell key={i} fill={COLORS[i%COLORS.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="panel"><h3>Category Breakdown</h3><table><tbody>{stats.byCategory.map(c=><tr key={c.category}><td>{c.category}</td><td>{c.count}건</td><td>₩{c.amount.toLocaleString()}</td></tr>)}</tbody></table></div></div></section> }
function DataTable({ rows, allRows, setRows, fields, labels, query, setQuery, reset, placeholder, moneyFields=[] }){ return <section className="panel"><div className="toolbar"><label><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={placeholder}/></label><button className="danger" onClick={()=>{ if(confirm('샘플 데이터로 초기화할까요?')) reset(); }}><Trash2 size={16}/> Reset</button></div><div className="tableWrap"><table><thead><tr>{fields.map(f=><th key={f}>{labels[f]}</th>)}<th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}>{fields.map(f=><td key={f}>{moneyFields.includes(f) ? Number(r[f]||0).toLocaleString() : r[f]}</td>)}<td><button className="mini" onClick={()=>setRows(allRows.filter(x=>x.id!==r.id))}>삭제</button></td></tr>)}</tbody></table></div></section>; }
function RecordForm({ fields, labels, form, setForm, submit, required }){ return <section className="panel"><form className="form" onSubmit={submit}>{fields.map(f=><label key={f}>{labels[f]}<input value={form[f] ?? ''} onChange={e=>setForm({...form,[f]:e.target.value})} required={required.includes(f)} /></label>)}<button className="primary"><PlusCircle size={18}/> 등록하기</button></form></section>; }
function UploadPanel({ type, onUpload, result, desc }){ return <section className="panel upload"><Upload size={48}/><h3>엑셀 파일 업로드</h3><p>{desc}</p><input type="file" accept=".xlsx,.xls,.csv" onChange={e=>onUpload(e,type)}/>{result && result.type===type && <div className="result"><CheckCircle2/> 전체 {result.total}건 / 신규 {result.inserted}건 / 중복 제외 {result.duplicated}건</div>}<div className="notice"><AlertTriangle/> 원본 컬럼은 유지하고 Normalized KRW / FX Rate 컬럼을 추가해 비교 기준을 통일했습니다.</div></section>; }
export default App;
